sudo: required
services:
  - docker

before_install:
  - docker build -t radomir/frontend -f Dockerfile.dev .

script:
  - docker run radomir/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "automatic-deploy"
  env: "AutomaticDeploy-env"
  bucket: "elasticbeanstalk-us-east-1-154909137467"
  bucket_path: "automatic-deploy"
  on:
    branch: master
  access_key_id: "AWS_SECRET_KEY"
  secret_access_key:
    secure: "AWS_SECRET_KEY"